### ISSUE TITLE
Model files do not match HuggingFace repository files

### ISSUE THREAD

**Issue by bobbythegreen** [nutanix/nai-llm#40]
python3 $WORK_DIR/llm/generate.py --model_name llama2_7b_chat --model_path $MODEL_PATH --mar_output $MODEL_STORE --hf_token hf_<token> returns an error:

Model files do not match HuggingFace repository files

then I cannot run the inference script:

bash $WORK_DIR/llm/run.sh -n llama2_7b_chat -a $MODEL_STORE

Running the Inference script

## Number of GPUs used: 1

Filepath does not exist MAR file - /home/rla/models/model_files_store/llama2_7b_chat_94b07a6.mar

**Comment by mal-sa** [comment]
didn't went deep to the root cause, but the issue is that an additional directory is being added to the downloaded version of the HF repo in your model directory ".huggingface" you can delete it manually and then run generate.py again with "--skip_download" option.
![image](https://github.com/nutanix/nai-llm/assets/168685022/69c35fb5-5f48-4baa-bdfa-1802dd9eb73f)

**Comment by robertolaverde** [comment]
Thanks, that did the trick!

**Comment by bobbythegreen** [comment]
Thanks, that did the trick!
